# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 69f71249452e2c26f6d32e509c7928282c141aa7c89239420b236be537c9f041c30a9824b54d73f61a064d378dcc94b4c80fb13c3edf43365a89077c9600adc2

test:
  secret_key_base: d1d52a3f92e0a1dfd61f13e902918d3314c15b4a7cf44829d6d3a0e66b81287e0ba03e6d89c062dcdae90779f36f0b1c6d908b782e9ae088da78b1ccd4b7f1be

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
